import { jsPDF } from 'jspdf';
import { formatDate, todayStr } from './dateFormat.js';
import { INTER_BOLD, INTER_REGULAR, INTER_SEMIBOLD } from './fonts/interFonts.js';

const MARGIN = 22; // spec: 20-25mm
const PAGE_WIDTH = 210; // A4 portrait, mm
const PAGE_HEIGHT = 297;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

// Design system (spec): dark, minimalist executive theme that mirrors the
// app's own UI (near-black page, off-white text, violet/cyan brand accent)
// instead of a generic light "corporate report" look. No decorative card
// backgrounds or borders anywhere — hierarchy comes from type weight, color,
// and whitespace alone. Exactly four status colors are reserved for
// communicating status (schedule/cost/quality, KPI health, budget state,
// risk severity) — no per-"kind" rainbow coding, and the brand accent
// (violet/cyan) is never used to mean a status.
const COLOR = {
  bg: [0x08, 0x0a, 0x0f], // #080a0f — matches app's --bg
  text: [0xf6, 0xf7, 0xfb], // #f6f7fb — matches app's --text
  textSecondary: [0x8b, 0x93, 0xa7], // #8b93a7 — matches app's --muted
  border: [0x25, 0x28, 0x30], // subtle hairline against near-black
  accent: [0x8b, 0x5c, 0xf6], // brand violet (app focus ring / logo family)
  green: [0x34, 0xd3, 0x99],
  amber: [0xfb, 0xbf, 0x24],
  red: [0xf8, 0x71, 0x71],
};

const SEVERITY_ORDER = { High: 0, Medium: 1, Low: 2 };

function slugify(text) {
  return (text || 'untitled')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}

function fmtNum(n) {
  return Number(n).toLocaleString('en-GB');
}

// jsPDF only ships the 14 standard PDF fonts (Helvetica etc.) — Inter is
// embedded per-document from a pre-subset base64 TTF (see fonts/interFonts.js,
// regenerated by scripts/build-pdf-fonts.sh) so exports read as a modern
// sans-serif report rather than a stock PDF-library look.
function registerFonts(doc) {
  doc.addFileToVFS('Inter-Regular.ttf', INTER_REGULAR);
  doc.addFont('Inter-Regular.ttf', 'Inter', 'normal');
  doc.addFileToVFS('Inter-SemiBold.ttf', INTER_SEMIBOLD);
  doc.addFont('Inter-SemiBold.ttf', 'Inter', 'semibold');
  doc.addFileToVFS('Inter-Bold.ttf', INTER_BOLD);
  doc.addFont('Inter-Bold.ttf', 'Inter', 'bold');
  doc.setFont('Inter', 'normal');
}

function setText(doc, size, weight, color) {
  doc.setFont('Inter', weight);
  doc.setFontSize(size);
  doc.setTextColor(...color);
}

// Every page is filled dark before content is drawn on it — jsPDF pages are
// white by default, and this must run on every addPage(), not just the
// first, or auto page-breaks (via ensureRoom) would leave a stray white page.
function fillPageBackground(doc) {
  doc.setFillColor(...COLOR.bg);
  doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');
}

function addPage(doc) {
  doc.addPage();
  fillPageBackground(doc);
}

// The only place color communicates meaning (schedule/cost/quality, KPI
// health, budget state, risk severity, decision markers) funnels through
// this one map, so "red always means the same thing" everywhere in the report.
function statusVisual(status) {
  switch (status) {
    case 'green':
      return { fg: COLOR.green, label: 'On Track' };
    case 'amber':
      return { fg: COLOR.amber, label: 'At Risk' };
    case 'red':
      return { fg: COLOR.red, label: 'Critical' };
    case 'blue':
      return { fg: COLOR.accent, label: 'Info' };
    default:
      return { fg: COLOR.textSecondary, label: 'N/A' };
  }
}

function fractionStatus(done, total) {
  if (total === 0) return 'n/a';
  if (done === total) return 'green';
  if (done === 0) return 'red';
  return 'amber';
}

function isOverdue(item, today) {
  return !!item.due_date && !item.done && item.due_date < today;
}

// Breaks to a new page if there's not enough room left for at least a
// section header and its first row, so headers never get orphaned alone at
// the bottom of a page with their content stranded on the next one.
function ensureRoom(doc, y, minSpace = 30) {
  if (y > PAGE_HEIGHT - minSpace) {
    addPage(doc);
    return MARGIN + 4;
  }
  return y;
}

// Plain muted text line, not a bordered/filled placeholder box — empty
// sections should read as quiet, not as another card competing for attention.
function drawEmptyState(doc, y, text) {
  y = ensureRoom(doc, y, 16);
  setText(doc, 9.5, 'normal', COLOR.textSecondary);
  doc.text(text, MARGIN, y + 2);
  return y + 14;
}

// Dot + bold colored label — no filled pill behind it, so status reads as
// text-with-emphasis rather than another decorative chip.
function drawStatusBadge(doc, x, y, status, labelOverride) {
  const sv = statusVisual(status);
  const label = labelOverride ?? sv.label;
  doc.setFillColor(...sv.fg);
  doc.circle(x + 1.4, y + 4, 1.5, 'F');
  setText(doc, 10.5, 'bold', sv.fg);
  doc.text(label, x + 6, y + 5.5);
  return doc.getTextWidth(label) + 6;
}

// Cover block: small tracked eyebrow, big bold title, a thin brand-accent
// rule, a metadata line, and an optional overall-status marker — once per
// document, not repeated as a banner on every page.
function drawReportHeader(doc, { eyebrow, title, generatedLabel, overallStatus }) {
  let y = MARGIN + 3;
  setText(doc, 10, 'semibold', COLOR.textSecondary);
  doc.text(eyebrow.toUpperCase(), MARGIN, y, { charSpace: 0.8 });
  y += 12;

  setText(doc, 30, 'bold', COLOR.text);
  const titleLines = doc.splitTextToSize(title, CONTENT_WIDTH);
  doc.text(titleLines, MARGIN, y);
  y += titleLines.length * 11 + 5;

  doc.setFillColor(...COLOR.accent);
  doc.rect(MARGIN, y, 16, 1.1, 'F');
  y += 8;

  setText(doc, 10.5, 'normal', COLOR.textSecondary);
  doc.text(generatedLabel, MARGIN, y);
  y += 7;

  if (overallStatus) {
    setText(doc, 10.5, 'normal', COLOR.textSecondary);
    doc.text('Overall Status', MARGIN, y + 5.5);
    const labelX = MARGIN + doc.getTextWidth('Overall Status') + 5;
    drawStatusBadge(doc, labelX, y, overallStatus.status, overallStatus.labelOverride);
    y += 15;
  } else {
    y += 6;
  }

  doc.setDrawColor(...COLOR.border);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  return y + 14;
}

// Page numbers only — no repeated "Generated" date on every page, since the
// generation date already appears once on the cover.
function addFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(...COLOR.border);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, PAGE_HEIGHT - 15, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 15);
    setText(doc, 8, 'normal', COLOR.textSecondary);
    doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 10, { align: 'right' });
  }
}

// 18pt bold section heading, marked with a small brand-accent tick instead
// of a rule/box, with generous whitespace above/below so sections never sit
// directly adjacent to one another.
function drawSectionHeader(doc, y, title) {
  y = ensureRoom(doc, y + 8, 45);
  doc.setFillColor(...COLOR.accent);
  doc.rect(MARGIN, y - 5.5, 1.2, 6.5, 'F');
  setText(doc, 18, 'bold', COLOR.text);
  doc.text(title, MARGIN + 5, y);
  return y + 12;
}

// Portfolio Health as a single row of plain stat blocks (label / big number /
// status dot) separated by hairline dividers — no card borders or fills, so
// aggregated data reads as one unified overview rather than scattered tiles.
function drawKpiCards(doc, y, cards) {
  y = ensureRoom(doc, y, 40);
  const gap = 8;
  const cardWidth = (CONTENT_WIDTH - gap * (cards.length - 1)) / cards.length;
  const blockHeight = 26;

  cards.forEach((card, i) => {
    const x = MARGIN + i * (cardWidth + gap);
    if (i > 0) {
      doc.setDrawColor(...COLOR.border);
      doc.setLineWidth(0.3);
      doc.line(x - gap / 2, y, x - gap / 2, y + blockHeight);
    }

    setText(doc, 7.5, 'semibold', COLOR.textSecondary);
    const labelLines = doc.splitTextToSize(card.label.toUpperCase(), cardWidth - 4).slice(0, 2);
    doc.text(labelLines, x, y + 6, { charSpace: 0.15 });

    setText(doc, 19, 'bold', COLOR.text);
    const valueStr = String(card.value);
    doc.text(valueStr, x, y + 20);

    const sv = statusVisual(card.status);
    doc.setFillColor(...sv.fg);
    doc.circle(x + doc.getTextWidth(valueStr) + 4.5, y + 17.3, 1.6, 'F');
  });

  return y + blockHeight + 13;
}

// Project identity + a strict two-row table: labeled fields (lead/dates),
// then Schedule/Budget/Quality as a column-divided row with bold colored
// status words — a clean table instead of a bordered/filled summary card.
function drawProjectSummaryPanel(doc, y, project) {
  y = ensureRoom(doc, y, 55);

  setText(doc, 15, 'bold', COLOR.text);
  doc.text(project.name, MARGIN, y);
  y += 9;

  doc.setDrawColor(...COLOR.border);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 9;

  const fieldW = CONTENT_WIDTH / 3;
  const fields = [
    ['Lead', project.lead?.name ?? '—'],
    ['Start Date', formatDate(project.start_date)],
    ['Target Date', formatDate(project.target_end_date)],
  ];
  fields.forEach(([label, value], i) => {
    const fx = MARGIN + i * fieldW;
    setText(doc, 7.5, 'semibold', COLOR.textSecondary);
    doc.text(label.toUpperCase(), fx, y, { charSpace: 0.2 });
    setText(doc, 10.5, 'normal', COLOR.text);
    doc.text(value, fx, y + 5.5);
  });
  y += 13;

  doc.setDrawColor(...COLOR.border);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 9;

  const metricW = CONTENT_WIDTH / 3;
  [
    ['Schedule', project.scorecard?.schedule],
    ['Budget', project.scorecard?.cost],
    ['Quality', project.scorecard?.quality],
  ].forEach(([label, status], i) => {
    const fx = MARGIN + i * metricW;
    if (i > 0) {
      doc.setDrawColor(...COLOR.border);
      doc.setLineWidth(0.3);
      doc.line(fx - 6, y - 6, fx - 6, y + 8);
    }
    const sv = statusVisual(status ?? 'n/a');
    setText(doc, 7.5, 'semibold', COLOR.textSecondary);
    doc.text(label.toUpperCase(), fx, y, { charSpace: 0.2 });
    doc.setFillColor(...sv.fg);
    doc.circle(fx + 1.3, y + 6.8, 1.5, 'F');
    setText(doc, 10.5, 'bold', sv.fg);
    doc.text(sv.label, fx + 5, y + 8);
  });
  y += 13;

  doc.setDrawColor(...COLOR.border);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  return y + 13;
}

// Budget bar: an outlined track (not a filled grey box) so the colored fill
// is the only thing carrying weight against the dark page — high contrast
// without a decorative background.
function drawBudgetSection(doc, y, project) {
  y = drawSectionHeader(doc, y, 'Budget');

  const spent = project.budget_spent ?? 0;
  const planned = project.budget_planned;

  if (planned == null) {
    setText(doc, 10, 'normal', COLOR.textSecondary);
    doc.text('No budget defined.', MARGIN, y);
    return y + 14;
  }

  const pct = planned > 0 ? spent / planned : 0;
  const over = spent > planned;

  setText(doc, 11.5, 'bold', COLOR.text);
  doc.text(fmtNum(spent), MARGIN, y);
  const spentW = doc.getTextWidth(fmtNum(spent));
  setText(doc, 11.5, 'normal', COLOR.textSecondary);
  doc.text(` of ${fmtNum(planned)}`, MARGIN + spentW, y);
  y += 7;

  const barH = 4;
  doc.setDrawColor(...COLOR.border);
  doc.setLineWidth(0.4);
  doc.roundedRect(MARGIN, y, CONTENT_WIDTH, barH, 2, 2, 'D');
  const fillW = Math.max(barH, CONTENT_WIDTH * Math.min(pct, 1));
  doc.setFillColor(...(over ? COLOR.red : COLOR.green));
  doc.roundedRect(MARGIN, y, fillW, barH, 2, 2, 'F');
  y += barH + 6;

  setText(doc, 9, 'bold', over ? COLOR.red : COLOR.textSecondary);
  doc.text(
    over
      ? `Over budget by ${fmtNum(spent - planned)} (${Math.round(pct * 100)}%)`
      : `${Math.round(pct * 100)}% of budget used`,
    MARGIN,
    y,
  );
  return y + 14;
}

// Risks/issues as a plain bulleted list — a colored severity dot, bold
// severity + owner line, then the description — separated by hairlines
// instead of individual bordered/filled cards.
function drawRiskCards(doc, y, risks, emptyLabel) {
  if (risks.length === 0) return drawEmptyState(doc, y, emptyLabel);

  risks.forEach((r, i) => {
    const lines = doc.splitTextToSize(r.text, CONTENT_WIDTH - 10);
    const rowH = lines.length * 5 + 9;
    y = ensureRoom(doc, y, rowH + 8);

    const dotColor = r.severity === 'High' ? COLOR.red : r.severity === 'Medium' ? COLOR.amber : COLOR.textSecondary;
    doc.setFillColor(...dotColor);
    doc.circle(MARGIN + 1.3, y + 1.3, 1.5, 'F');

    setText(doc, 9, 'bold', dotColor);
    const sevLabel = `${r.severity.toUpperCase()} SEVERITY`;
    doc.text(sevLabel, MARGIN + 6, y + 2);
    const sevW = doc.getTextWidth(sevLabel);

    const metaParts = [r.owner_name || 'Unassigned'];
    if (r.resolved !== undefined) metaParts.push(r.resolved ? 'Resolved' : 'Open');
    setText(doc, 9, 'normal', COLOR.textSecondary);
    doc.text(`·   ${metaParts.join('   ·   ')}`, MARGIN + 6 + sevW + 4, y + 2);

    setText(doc, 10, 'normal', r.resolved ? COLOR.textSecondary : COLOR.text);
    doc.text(lines, MARGIN + 6, y + 8);

    y += rowH + 6;
    if (i < risks.length - 1) {
      doc.setDrawColor(...COLOR.border);
      doc.setLineWidth(0.2);
      doc.line(MARGIN, y - 3, PAGE_WIDTH - MARGIN, y - 3);
    }
  });
  return y + 4;
}

// Strict labeled list (header row + hairline + rows); overdue due-dates
// render bold red so the one thing that needs attention is unmissable.
function drawTaskList(doc, y, tasks, emptyLabel) {
  y = ensureRoom(doc, y, 30);
  setText(doc, 8, 'semibold', COLOR.textSecondary);
  doc.text('DUE DATE', MARGIN, y, { charSpace: 0.2 });
  doc.text('OWNER', MARGIN + 30, y, { charSpace: 0.2 });
  doc.text('TASK', MARGIN + 65, y, { charSpace: 0.2 });
  y += 3;
  doc.setDrawColor(...COLOR.border);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 7;

  if (tasks.length === 0) return drawEmptyState(doc, y - 3, emptyLabel);

  tasks.forEach((t, i) => {
    const lines = doc.splitTextToSize(t.text, CONTENT_WIDTH - 65);
    const rowH = Math.max(7, lines.length * 5);
    y = ensureRoom(doc, y, rowH + 12);

    setText(doc, 9.5, t.overdue ? 'bold' : 'normal', t.overdue ? COLOR.red : COLOR.textSecondary);
    doc.text(t.dueLabel, MARGIN, y);
    setText(doc, 9.5, 'normal', COLOR.textSecondary);
    doc.text(t.owner, MARGIN + 30, y);
    setText(doc, 10, t.overdue ? 'bold' : 'normal', t.overdue ? COLOR.red : COLOR.text);
    doc.text(lines, MARGIN + 65, y);

    y += rowH + 5;
    if (i < tasks.length - 1) {
      doc.setDrawColor(...COLOR.border);
      doc.setLineWidth(0.2);
      doc.line(MARGIN, y - 2.5, PAGE_WIDTH - MARGIN, y - 2.5);
    }
  });
  return y + 6;
}

// Requirements/Goals: a bold "X of Y complete" roll-up + thin progress bar
// up top (so the aggregate is the first thing read), then the itemized list
// below — kept, since the underlying text must not be dropped, but with a
// minimal open/filled dot instead of a bordered checkbox glyph.
function drawChecklist(doc, y, items, emptyLabel) {
  y = ensureRoom(doc, y, 30);
  const total = items.length;
  const done = items.filter((it) => it.done).length;
  const pct = total > 0 ? Math.round((done / total) * 100) : 0;

  setText(doc, 11, 'bold', COLOR.text);
  doc.text(total > 0 ? `${done} of ${total} complete` : emptyLabel, MARGIN, y);

  if (total > 0) {
    setText(doc, 11, 'bold', pct === 100 ? COLOR.green : COLOR.textSecondary);
    doc.text(`${pct}%`, PAGE_WIDTH - MARGIN, y, { align: 'right' });
    y += 5;
    const barW = 50;
    const barX = PAGE_WIDTH - MARGIN - barW;
    doc.setDrawColor(...COLOR.border);
    doc.setLineWidth(0.4);
    doc.roundedRect(barX, y - 2.6, barW, 2.6, 1.3, 1.3, 'D');
    doc.setFillColor(...(pct === 100 ? COLOR.green : COLOR.accent));
    doc.roundedRect(barX, y - 2.6, Math.max(2.6, (barW * pct) / 100), 2.6, 1.3, 1.3, 'F');
  }
  y += 10;

  if (total === 0) return y + 4;

  items.forEach((it) => {
    const lines = doc.splitTextToSize(it.text, CONTENT_WIDTH - (it.meta ? 50 : 8));
    const rowH = Math.max(6.5, lines.length * 5);
    y = ensureRoom(doc, y, rowH + 8);

    doc.setLineWidth(0.5);
    if (it.done) {
      doc.setFillColor(...COLOR.green);
      doc.circle(MARGIN + 1.3, y - 1.6, 1.5, 'F');
    } else {
      doc.setDrawColor(...COLOR.border);
      doc.circle(MARGIN + 1.3, y - 1.6, 1.5, 'D');
    }

    setText(doc, 10, 'normal', it.done ? COLOR.textSecondary : COLOR.text);
    doc.text(lines, MARGIN + 7, y);
    if (it.meta) {
      setText(doc, 8.5, 'normal', COLOR.textSecondary);
      doc.text(it.meta, PAGE_WIDTH - MARGIN, y, { align: 'right' });
    }
    y += rowH + 4;
  });
  return y + 6;
}

// Decisions as a vertical timeline: connecting line down the left edge, a
// brand-accent dot per entry, bold date, then the decision text and who made
// it — generously spaced so entries never crowd each other.
function drawDecisionTimeline(doc, y, decisions, emptyLabel) {
  if (decisions.length === 0) return drawEmptyState(doc, y, emptyLabel);

  const dotX = MARGIN + 2;
  decisions.forEach((d, i) => {
    const lines = doc.splitTextToSize(d.text, CONTENT_WIDTH - 16);
    const blockH = lines.length * 5 + 14;
    y = ensureRoom(doc, y, blockH + 12);

    doc.setFillColor(...COLOR.accent);
    doc.circle(dotX, y + 1, 1.5, 'F');
    if (i < decisions.length - 1) {
      doc.setDrawColor(...COLOR.border);
      doc.setLineWidth(0.5);
      doc.line(dotX, y + 3, dotX, y + blockH + 3);
    }

    setText(doc, 9, 'bold', COLOR.textSecondary);
    doc.text(d.dateLabel, MARGIN + 9, y + 1.5);
    setText(doc, 10.5, 'normal', COLOR.text);
    doc.text(lines, MARGIN + 9, y + 7.5);
    setText(doc, 8.5, 'normal', COLOR.textSecondary);
    doc.text(`Decided by ${d.decidedBy || '—'}`, MARGIN + 9, y + 7.5 + lines.length * 5 + 3);

    y += blockH + 8;
  });
  return y + 4;
}

// Per-event "meeting minutes" style export: title/project/date header, then
// the decisions/action items/pain points logged against that event.
export function generateEventProtocolPdf(event) {
  const doc = new jsPDF();
  registerFonts(doc);
  fillPageBackground(doc);

  const overallStatus =
    event.status && event.status !== 'pending'
      ? {
          status: event.status === 'achieved' ? 'green' : 'red',
          labelOverride: event.status === 'achieved' ? 'Achieved' : 'Missed',
        }
      : null;

  let y = drawReportHeader(doc, {
    eyebrow: 'Event Protocol',
    title: event.title,
    generatedLabel: `${event.project?.name ?? ''}   ·   ${event.type}   ·   ${formatDate(event.date)}`,
    overallStatus,
  });

  if (event.summary) {
    setText(doc, 10.5, 'normal', COLOR.text);
    const lines = doc.splitTextToSize(event.summary, CONTENT_WIDTH);
    doc.text(lines, MARGIN, y);
    y += lines.length * 5.2 + 4;
  }

  const participantNames = (event.participants || []).map((p) => p.name).join(', ');
  setText(doc, 9, 'normal', COLOR.textSecondary);
  doc.text(`Participants: ${participantNames || '—'}`, MARGIN, y);
  y += 6;

  y = drawSectionHeader(doc, y, 'Decisions');
  y = drawDecisionTimeline(
    doc,
    y,
    (event.decisions || []).map((d) => ({
      dateLabel: formatDate(event.date),
      text: d.text,
      decidedBy: d.decided_by_name,
    })),
    'No decisions logged.',
  );

  y = drawSectionHeader(doc, y, 'Action Items');
  y = drawChecklist(
    doc,
    y,
    (event.action_items || []).map((a) => ({
      done: a.done,
      text: a.text,
      meta: [a.assignee_name, a.due_date ? formatDate(a.due_date) : null].filter(Boolean).join('   ·   ') || null,
    })),
    'No action items.',
  );

  y = drawSectionHeader(doc, y, 'Pain Points');
  y = drawRiskCards(
    doc,
    y,
    (event.pain_points || []).map((p) => ({
      text: p.text,
      severity: p.severity,
      owner_name: p.owner_name,
      resolved: p.resolved,
    })),
    'No pain points.',
  );

  addFooter(doc);
  doc.save(`Protokoll_${slugify(event.title)}_${event.date}.pdf`);
}

// Executive-style status report scoped to whichever projects are currently
// selected — a shared Portfolio Health cover, then each project gets its own
// two-page spread (summary/budget/risks/actions, then requirements/goals/
// decisions), matching how a PM would hand this to management per project.
export function generateSituationReportPdf({ projects, events, summary }) {
  const doc = new jsPDF();
  registerFonts(doc);
  fillPageBackground(doc);
  const today = todayStr();

  const totalRequirements = projects.reduce((sum, p) => sum + (p.requirements?.length ?? 0), 0);
  const doneRequirements = projects.reduce((sum, p) => sum + (p.requirements?.filter((r) => r.done).length ?? 0), 0);
  const totalGoals = projects.reduce((sum, p) => sum + (p.goals?.length ?? 0), 0);
  const achievedGoals = projects.reduce((sum, p) => sum + (p.goals?.filter((g) => g.achieved).length ?? 0), 0);

  const dims = projects.flatMap((p) => ['schedule', 'cost', 'quality'].map((k) => p.scorecard?.[k]));
  const overallStatus = dims.includes('red') ? 'red' : dims.includes('amber') ? 'amber' : 'green';

  let y = drawReportHeader(doc, {
    eyebrow: 'Status Report',
    title: projects.length === 1 ? projects[0].name : 'Overall Situation Report',
    generatedLabel: `Generated ${formatDate(today)}   ·   ${projects.map((p) => p.name).join(', ')}`,
    overallStatus: { status: overallStatus },
  });

  y = drawSectionHeader(doc, y, 'Portfolio Health');
  y = drawKpiCards(doc, y, [
    {
      value: summary.overdue_action_items,
      label: 'Overdue Tasks',
      status: summary.overdue_action_items > 0 ? 'red' : 'green',
    },
    {
      value: summary.open_high_severity_pain_points,
      label: 'High Severity Risks',
      status: summary.open_high_severity_pain_points > 0 ? 'red' : 'green',
    },
    {
      value: summary.upcoming_deadlines,
      label: 'Upcoming Milestones',
      status: summary.upcoming_deadlines > 0 ? 'blue' : 'green',
    },
    {
      value: `${doneRequirements}/${totalRequirements}`,
      label: 'Requirements Fulfilled',
      status: fractionStatus(doneRequirements, totalRequirements),
    },
    {
      value: `${achievedGoals}/${totalGoals}`,
      label: 'Goals Achieved',
      status: fractionStatus(achievedGoals, totalGoals),
    },
  ]);

  projects.forEach((project, idx) => {
    if (idx > 0) {
      addPage(doc);
      y = MARGIN + 4;
    } else {
      y = ensureRoom(doc, y, 40);
    }

    const projectEvents = events.filter((e) => e.project_id === project.id);

    y = drawProjectSummaryPanel(doc, y, project);
    y = drawBudgetSection(doc, y, project);

    const openRisks = projectEvents
      .flatMap((e) => e.pain_points.filter((p) => !p.resolved).map((p) => p))
      .sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]);
    y = drawSectionHeader(doc, y, 'Top Risks');
    y = drawRiskCards(doc, y, openRisks, 'No open risks or issues.');

    const openActions = projectEvents
      .flatMap((e) => e.action_items.filter((a) => !a.done))
      .sort((a, b) => (a.due_date || '9999').localeCompare(b.due_date || '9999'));
    y = drawSectionHeader(doc, y, 'Outstanding Actions');
    y = drawTaskList(
      doc,
      y,
      openActions.map((a) => ({
        dueLabel: a.due_date ? formatDate(a.due_date) : '—',
        owner: a.assignee_name || '—',
        text: a.text,
        overdue: isOverdue(a, today),
      })),
      'No open action items.',
    );

    addPage(doc);
    y = MARGIN + 4;

    y = drawSectionHeader(doc, y, 'Requirements');
    y = drawChecklist(
      doc,
      y,
      (project.requirements ?? []).map((r) => ({ done: r.done, text: r.text })),
      'No requirements defined.',
    );

    y = drawSectionHeader(doc, y, 'Goals');
    y = drawChecklist(
      doc,
      y,
      (project.goals ?? []).map((g) => ({
        done: g.achieved,
        text: g.text,
        meta: g.target_date ? formatDate(g.target_date) : null,
      })),
      'No goals defined.',
    );

    const decisions = projectEvents
      .flatMap((e) => e.decisions.map((d) => ({ ...d, eventDate: e.date })))
      .sort((a, b) => a.eventDate.localeCompare(b.eventDate));
    y = drawSectionHeader(doc, y, 'Decisions');
    y = drawDecisionTimeline(
      doc,
      y,
      decisions.map((d) => ({ dateLabel: formatDate(d.eventDate), text: d.text, decidedBy: d.decided_by_name })),
      'No decisions logged.',
    );
  });

  addFooter(doc);
  doc.save(`Statusbericht_${today}.pdf`);
}
