import { jsPDF } from 'jspdf';
import { formatDate, todayStr } from './dateFormat.js';
import { INTER_BOLD, INTER_REGULAR, INTER_SEMIBOLD } from './fonts/interFonts.js';

const MARGIN = 22; // spec: 20-25mm
const PAGE_WIDTH = 210; // A4 portrait, mm
const PAGE_HEIGHT = 297;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

// Executive-report palette (spec): white page, near-black text, grey secondary/
// borders/cards, and exactly four status colors reserved for communicating
// status — no per-"kind" rainbow coding like the previous design used.
const COLOR = {
  text: [0x20, 0x21, 0x24], // #202124
  textSecondary: [0x5f, 0x63, 0x68], // #5F6368
  border: [0xe6, 0xe6, 0xe6], // #E6E6E6
  card: [0xfa, 0xfa, 0xfa], // #FAFAFA
  green: [0x2e, 0x7d, 0x32],
  greenBg: [0xe8, 0xf5, 0xe9],
  amber: [0xf9, 0xa8, 0x25],
  amberBg: [0xff, 0xf8, 0xe1],
  red: [0xd3, 0x2f, 0x2f],
  redBg: [0xfd, 0xec, 0xea],
  blue: [0x15, 0x65, 0xc0],
  blueBg: [0xe3, 0xf2, 0xfd],
};

const SEVERITY_ORDER = { High: 0, Medium: 1, Low: 2 };

function slugify(text) {
  return (text || 'untitled')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
}

function fmtNum(n) {
  return Number(n).toLocaleString('en-GB');
}

// jsPDF only ships the 14 standard PDF fonts (Helvetica etc.) — Inter is
// embedded per-document from a pre-subset base64 TTF (see fonts/interFonts.js,
// regenerated by scripts/build-pdf-fonts.sh) so exports read as a modern
// sans-serif report rather than a stock PDF-library look.
function registerFonts(doc) {
  doc.addFileToVFS('Inter-Regular.ttf', INTER_REGULAR);
  doc.addFont('Inter-Regular.ttf', 'Inter', 'normal');
  doc.addFileToVFS('Inter-SemiBold.ttf', INTER_SEMIBOLD);
  doc.addFont('Inter-SemiBold.ttf', 'Inter', 'semibold');
  doc.addFileToVFS('Inter-Bold.ttf', INTER_BOLD);
  doc.addFont('Inter-Bold.ttf', 'Inter', 'bold');
  doc.setFont('Inter', 'normal');
}

function setText(doc, size, weight, color) {
  doc.setFont('Inter', weight);
  doc.setFontSize(size);
  doc.setTextColor(...color);
}

// The only place color communicates meaning (schedule/cost/quality, KPI
// health, budget state, risk severity, decision markers) funnels through
// this one map, so "red always means the same thing" everywhere in the report.
function statusVisual(status) {
  switch (status) {
    case 'green':
      return { fg: COLOR.green, bg: COLOR.greenBg, label: 'On Track' };
    case 'amber':
      return { fg: COLOR.amber, bg: COLOR.amberBg, label: 'At Risk' };
    case 'red':
      return { fg: COLOR.red, bg: COLOR.redBg, label: 'Critical' };
    case 'blue':
      return { fg: COLOR.blue, bg: COLOR.blueBg, label: 'Info' };
    default:
      return { fg: COLOR.textSecondary, bg: COLOR.card, label: 'N/A' };
  }
}

function fractionStatus(done, total) {
  if (total === 0) return 'n/a';
  if (done === total) return 'green';
  if (done === 0) return 'red';
  return 'amber';
}

function isOverdue(item, today) {
  return !!item.due_date && !item.done && item.due_date < today;
}

// Breaks to a new page if there's not enough room left for at least a
// section header and its first row, so headers never get orphaned alone at
// the bottom of a page with their content stranded on the next one.
function ensureRoom(doc, y, minSpace = 30) {
  if (y > PAGE_HEIGHT - minSpace) {
    doc.addPage();
    return MARGIN + 4;
  }
  return y;
}

function drawEmptyState(doc, y, text) {
  y = ensureRoom(doc, y, 20);
  doc.setDrawColor(...COLOR.border);
  doc.setFillColor(...COLOR.card);
  doc.setLineWidth(0.3);
  doc.roundedRect(MARGIN, y - 4, CONTENT_WIDTH, 11, 2, 2, 'FD');
  setText(doc, 9.5, 'normal', COLOR.textSecondary);
  doc.text(text, MARGIN + 4, y + 2.3);
  return y + 16;
}

function drawStatusBadge(doc, x, y, status, labelOverride) {
  const sv = statusVisual(status);
  const label = labelOverride ?? sv.label;
  setText(doc, 9, 'semibold', sv.fg);
  const badgeW = doc.getTextWidth(label) + 13;
  doc.setFillColor(...sv.bg);
  doc.roundedRect(x, y, badgeW, 8, 4, 4, 'F');
  doc.setFillColor(...sv.fg);
  doc.circle(x + 5.5, y + 4, 1.3, 'F');
  doc.text(label, x + 9, y + 5.5);
  return badgeW;
}

// Cover block: small tracked eyebrow, big bold title, a metadata line, and an
// optional overall-status badge — once per document, not repeated as a
// banner on every page like the previous dark-theme design.
function drawReportHeader(doc, { eyebrow, title, generatedLabel, overallStatus }) {
  let y = MARGIN + 3;
  setText(doc, 10, 'semibold', COLOR.textSecondary);
  doc.text(eyebrow.toUpperCase(), MARGIN, y, { charSpace: 0.8 });
  y += 12;

  setText(doc, 30, 'bold', COLOR.text);
  const titleLines = doc.splitTextToSize(title, CONTENT_WIDTH);
  doc.text(titleLines, MARGIN, y);
  y += titleLines.length * 11 + 3;

  setText(doc, 10.5, 'normal', COLOR.textSecondary);
  doc.text(generatedLabel, MARGIN, y);
  y += 7;

  if (overallStatus) {
    setText(doc, 10.5, 'normal', COLOR.textSecondary);
    doc.text('Overall Status', MARGIN, y + 5.5);
    const labelX = MARGIN + doc.getTextWidth('Overall Status') + 5;
    drawStatusBadge(doc, labelX, y, overallStatus.status, overallStatus.labelOverride);
    y += 14;
  } else {
    y += 5;
  }

  doc.setDrawColor(...COLOR.border);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  return y + 13;
}

function addFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setDrawColor(...COLOR.border);
    doc.setLineWidth(0.3);
    doc.line(MARGIN, PAGE_HEIGHT - 15, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 15);
    setText(doc, 8, 'normal', COLOR.textSecondary);
    doc.text(`Generated ${formatDate(todayStr())}`, MARGIN, PAGE_HEIGHT - 10);
    doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN, PAGE_HEIGHT - 10, { align: 'right' });
  }
}

// 18-22pt bold section heading with breathing room above/below (spec:
// "plenty of whitespace", "never place sections directly adjacent").
function drawSectionHeader(doc, y, title) {
  y = ensureRoom(doc, y + 6, 45);
  setText(doc, 18, 'bold', COLOR.text);
  doc.text(title, MARGIN, y);
  return y + 11;
}

// One bordered tile per KPI: small caps label, big number, small status dot —
// mirrors the app's own dashboard stat tiles rather than a gridded table.
function drawKpiCards(doc, y, cards) {
  y = ensureRoom(doc, y, 40);
  const gap = 5;
  const cardWidth = (CONTENT_WIDTH - gap * (cards.length - 1)) / cards.length;
  const cardHeight = 28;

  cards.forEach((card, i) => {
    const x = MARGIN + i * (cardWidth + gap);
    doc.setDrawColor(...COLOR.border);
    doc.setLineWidth(0.3);
    doc.setFillColor(...COLOR.card);
    doc.roundedRect(x, y, cardWidth, cardHeight, 2, 2, 'FD');

    setText(doc, 7.5, 'semibold', COLOR.textSecondary);
    const labelLines = doc.splitTextToSize(card.label.toUpperCase(), cardWidth - 8).slice(0, 2);
    doc.text(labelLines, x + 4, y + 7, { charSpace: 0.15 });

    setText(doc, 18, 'bold', COLOR.text);
    const valueStr = String(card.value);
    doc.text(valueStr, x + 4, y + 20);

    const sv = statusVisual(card.status);
    doc.setFillColor(...sv.fg);
    doc.circle(x + 4 + doc.getTextWidth(valueStr) + 4.5, y + 17.3, 1.6, 'F');
  });

  return y + cardHeight + 12;
}

// Structured panel: project name, lead/dates as labeled fields, then
// schedule/cost/quality as large, immediately-recognisable colored dots
// rather than the word "Red" in a table cell.
function drawProjectSummaryPanel(doc, y, project) {
  y = ensureRoom(doc, y, 55);
  const panelH = 38;
  doc.setDrawColor(...COLOR.border);
  doc.setLineWidth(0.3);
  doc.setFillColor(...COLOR.card);
  doc.roundedRect(MARGIN, y, CONTENT_WIDTH, panelH, 2, 2, 'FD');

  const px = MARGIN + 7;
  let py = y + 11;
  setText(doc, 13, 'semibold', COLOR.text);
  doc.text(project.name, px, py);
  py += 10;

  const fieldW = (CONTENT_WIDTH - 14) / 3;
  const fields = [
    ['Lead', project.lead?.name ?? '—'],
    ['Start Date', formatDate(project.start_date)],
    ['Target Date', formatDate(project.target_end_date)],
  ];
  fields.forEach(([label, value], i) => {
    const fx = px + i * fieldW;
    setText(doc, 7.5, 'semibold', COLOR.textSecondary);
    doc.text(label.toUpperCase(), fx, py, { charSpace: 0.2 });
    setText(doc, 10, 'normal', COLOR.text);
    doc.text(value, fx, py + 5.5);
  });
  py += 13.5;

  ['schedule', 'cost', 'quality'].forEach((key, i) => {
    const fx = px + i * fieldW;
    const sv = statusVisual(project.scorecard?.[key] ?? 'n/a');
    doc.setFillColor(...sv.fg);
    doc.circle(fx + 2, py - 1.4, 2, 'F');
    setText(doc, 10, 'semibold', COLOR.text);
    doc.text(`${key[0].toUpperCase()}${key.slice(1)}`, fx + 6.5, py);
  });

  return y + panelH + 12;
}

function drawBudgetSection(doc, y, project) {
  y = drawSectionHeader(doc, y, 'Budget');

  const spent = project.budget_spent ?? 0;
  const planned = project.budget_planned;

  if (planned == null) {
    setText(doc, 10, 'normal', COLOR.textSecondary);
    doc.text('No budget defined.', MARGIN, y);
    return y + 14;
  }

  const pct = planned > 0 ? spent / planned : 0;
  const over = spent > planned;

  setText(doc, 11, 'normal', COLOR.text);
  doc.text(`${fmtNum(spent)} of ${fmtNum(planned)}`, MARGIN, y);
  y += 7;

  const barH = 5;
  doc.setFillColor(...COLOR.border);
  doc.roundedRect(MARGIN, y, CONTENT_WIDTH, barH, 2.5, 2.5, 'F');
  const fillW = Math.max(barH, CONTENT_WIDTH * Math.min(pct, 1));
  doc.setFillColor(...(over ? COLOR.red : COLOR.green));
  doc.roundedRect(MARGIN, y, fillW, barH, 2.5, 2.5, 'F');
  y += barH + 6;

  setText(doc, 9, 'semibold', over ? COLOR.red : COLOR.textSecondary);
  doc.text(
    over
      ? `Over budget by ${fmtNum(spent - planned)} (${Math.round(pct * 100)}%)`
      : `${Math.round(pct * 100)}% of budget used`,
    MARGIN,
    y,
  );
  return y + 14;
}

// Each risk/issue as its own card with a severity-colored left accent bar,
// instead of a table row — matches the spec's "prioritised list" ask.
function drawRiskCards(doc, y, risks, emptyLabel) {
  if (risks.length === 0) return drawEmptyState(doc, y, emptyLabel);

  risks.forEach((r) => {
    const lines = doc.splitTextToSize(r.text, CONTENT_WIDTH - 14);
    const cardH = Math.max(17, lines.length * 5 + 11);
    y = ensureRoom(doc, y, cardH + 10);

    const barColor = r.severity === 'High' ? COLOR.red : r.severity === 'Medium' ? COLOR.amber : COLOR.border;
    doc.setDrawColor(...COLOR.border);
    doc.setLineWidth(0.3);
    doc.setFillColor(...COLOR.card);
    doc.roundedRect(MARGIN, y, CONTENT_WIDTH, cardH, 2, 2, 'FD');
    doc.setFillColor(...barColor);
    doc.roundedRect(MARGIN, y, 2.2, cardH, 1, 1, 'F');

    setText(doc, 10, 'normal', r.resolved ? COLOR.textSecondary : COLOR.text);
    doc.text(lines, MARGIN + 7, y + 7);

    const metaParts = [`${r.severity} severity`, r.owner_name || 'Unassigned'];
    if (r.resolved !== undefined) metaParts.push(r.resolved ? 'Resolved' : 'Open');
    setText(doc, 8, 'normal', COLOR.textSecondary);
    doc.text(metaParts.join('   ·   '), MARGIN + 7, y + cardH - 4);

    y += cardH + 5;
  });
  return y + 5;
}

// Clean list (labeled header row + horizontal rule + rows) rather than a
// heavy-bordered table; overdue due-dates render in red automatically.
function drawTaskList(doc, y, tasks, emptyLabel) {
  y = ensureRoom(doc, y, 30);
  setText(doc, 8, 'semibold', COLOR.textSecondary);
  doc.text('DUE DATE', MARGIN, y, { charSpace: 0.2 });
  doc.text('OWNER', MARGIN + 30, y, { charSpace: 0.2 });
  doc.text('TASK', MARGIN + 65, y, { charSpace: 0.2 });
  y += 3;
  doc.setDrawColor(...COLOR.border);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y, PAGE_WIDTH - MARGIN, y);
  y += 7;

  if (tasks.length === 0) return drawEmptyState(doc, y - 3, emptyLabel);

  tasks.forEach((t, i) => {
    const lines = doc.splitTextToSize(t.text, CONTENT_WIDTH - 65);
    const rowH = Math.max(7, lines.length * 5);
    y = ensureRoom(doc, y, rowH + 12);

    setText(doc, 9.5, t.overdue ? 'semibold' : 'normal', t.overdue ? COLOR.red : COLOR.textSecondary);
    doc.text(t.dueLabel, MARGIN, y);
    setText(doc, 9.5, 'normal', COLOR.textSecondary);
    doc.text(t.owner, MARGIN + 30, y);
    setText(doc, 10, 'normal', COLOR.text);
    doc.text(lines, MARGIN + 65, y);

    y += rowH + 4;
    if (i < tasks.length - 1) {
      doc.setDrawColor(...COLOR.border);
      doc.setLineWidth(0.2);
      doc.line(MARGIN, y - 2, PAGE_WIDTH - MARGIN, y - 2);
      y += 2;
    }
  });
  return y + 6;
}

// Requirements/Goals as a checklist with a completion progress bar — hand-
// drawn checkbox glyphs (not unicode ☐/☑, which most PDF-embedded fonts
// don't carry) so the checked/unchecked state always renders reliably.
function drawChecklist(doc, y, items, emptyLabel) {
  y = ensureRoom(doc, y, 30);
  const total = items.length;
  const done = items.filter((it) => it.done).length;
  const pct = total > 0 ? Math.round((done / total) * 100) : 0;

  setText(doc, 9.5, 'normal', COLOR.textSecondary);
  doc.text(total > 0 ? `${done} of ${total} complete` : emptyLabel, MARGIN, y);

  if (total > 0) {
    setText(doc, 9.5, 'semibold', COLOR.textSecondary);
    doc.text(`${pct}%`, PAGE_WIDTH - MARGIN, y, { align: 'right' });
    y += 4;
    const barW = 50;
    const barX = PAGE_WIDTH - MARGIN - barW;
    doc.setFillColor(...COLOR.border);
    doc.roundedRect(barX, y - 2.6, barW, 2.6, 1.3, 1.3, 'F');
    doc.setFillColor(...(pct === 100 ? COLOR.green : COLOR.blue));
    doc.roundedRect(barX, y - 2.6, Math.max(2.6, (barW * pct) / 100), 2.6, 1.3, 1.3, 'F');
  }
  y += 9;

  if (total === 0) return y + 6;

  items.forEach((it) => {
    const lines = doc.splitTextToSize(it.text, CONTENT_WIDTH - (it.meta ? 50 : 8));
    const rowH = Math.max(6.5, lines.length * 5);
    y = ensureRoom(doc, y, rowH + 8);

    if (it.done) {
      doc.setFillColor(...COLOR.green);
      doc.roundedRect(MARGIN, y - 3.6, 4, 4, 0.8, 0.8, 'F');
      doc.setDrawColor(255, 255, 255);
      doc.setLineWidth(0.5);
      doc.line(MARGIN + 0.8, y - 1.7, MARGIN + 1.7, y - 0.7);
      doc.line(MARGIN + 1.7, y - 0.7, MARGIN + 3.3, y - 3.1);
    } else {
      doc.setDrawColor(...COLOR.border);
      doc.setLineWidth(0.5);
      doc.roundedRect(MARGIN, y - 3.6, 4, 4, 0.8, 0.8, 'D');
    }

    setText(doc, 10, 'normal', it.done ? COLOR.textSecondary : COLOR.text);
    doc.text(lines, MARGIN + 7, y);
    if (it.meta) {
      setText(doc, 8.5, 'normal', COLOR.textSecondary);
      doc.text(it.meta, PAGE_WIDTH - MARGIN, y, { align: 'right' });
    }
    y += rowH + 3.5;
  });
  return y + 6;
}

// Decisions as a vertical timeline: a connecting line down the left edge,
// a dot per entry, bold date, then the decision text and who made it.
function drawDecisionTimeline(doc, y, decisions, emptyLabel) {
  if (decisions.length === 0) return drawEmptyState(doc, y, emptyLabel);

  const dotX = MARGIN + 2;
  decisions.forEach((d, i) => {
    const lines = doc.splitTextToSize(d.text, CONTENT_WIDTH - 16);
    const blockH = lines.length * 5 + 11;
    y = ensureRoom(doc, y, blockH + 10);

    doc.setFillColor(...COLOR.blue);
    doc.circle(dotX, y + 1, 1.5, 'F');
    if (i < decisions.length - 1) {
      doc.setDrawColor(...COLOR.border);
      doc.setLineWidth(0.5);
      doc.line(dotX, y + 3, dotX, y + blockH + 1);
    }

    setText(doc, 9, 'semibold', COLOR.textSecondary);
    doc.text(d.dateLabel, MARGIN + 9, y + 1.5);
    setText(doc, 10.5, 'normal', COLOR.text);
    doc.text(lines, MARGIN + 9, y + 7.5);
    setText(doc, 8.5, 'normal', COLOR.textSecondary);
    doc.text(`Decided by ${d.decidedBy || '—'}`, MARGIN + 9, y + 7.5 + lines.length * 5 + 3);

    y += blockH + 6;
  });
  return y + 4;
}

// Per-event "meeting minutes" style export: title/project/date header, then
// the decisions/action items/pain points logged against that event.
export function generateEventProtocolPdf(event) {
  const doc = new jsPDF();
  registerFonts(doc);

  const overallStatus =
    event.status && event.status !== 'pending'
      ? {
          status: event.status === 'achieved' ? 'green' : 'red',
          labelOverride: event.status === 'achieved' ? 'Achieved' : 'Missed',
        }
      : null;

  let y = drawReportHeader(doc, {
    eyebrow: 'Event Protocol',
    title: event.title,
    generatedLabel: `${event.project?.name ?? ''}   ·   ${event.type}   ·   ${formatDate(event.date)}`,
    overallStatus,
  });

  if (event.summary) {
    setText(doc, 10.5, 'normal', COLOR.text);
    const lines = doc.splitTextToSize(event.summary, CONTENT_WIDTH);
    doc.text(lines, MARGIN, y);
    y += lines.length * 5.2 + 4;
  }

  const participantNames = (event.participants || []).map((p) => p.name).join(', ');
  setText(doc, 9, 'normal', COLOR.textSecondary);
  doc.text(`Participants: ${participantNames || '—'}`, MARGIN, y);
  y += 6;

  y = drawSectionHeader(doc, y, 'Decisions');
  y = drawDecisionTimeline(
    doc,
    y,
    (event.decisions || []).map((d) => ({
      dateLabel: formatDate(event.date),
      text: d.text,
      decidedBy: d.decided_by_name,
    })),
    'No decisions logged.',
  );

  y = drawSectionHeader(doc, y, 'Action Items');
  y = drawChecklist(
    doc,
    y,
    (event.action_items || []).map((a) => ({
      done: a.done,
      text: a.text,
      meta: [a.assignee_name, a.due_date ? formatDate(a.due_date) : null].filter(Boolean).join('   ·   ') || null,
    })),
    'No action items.',
  );

  y = drawSectionHeader(doc, y, 'Pain Points');
  y = drawRiskCards(
    doc,
    y,
    (event.pain_points || []).map((p) => ({
      text: p.text,
      severity: p.severity,
      owner_name: p.owner_name,
      resolved: p.resolved,
    })),
    'No pain points.',
  );

  addFooter(doc);
  doc.save(`Protokoll_${slugify(event.title)}_${event.date}.pdf`);
}

// Executive-style status report scoped to whichever projects are currently
// selected — a shared Portfolio Health cover, then each project gets its own
// two-page spread (summary/budget/risks/actions, then requirements/goals/
// decisions), matching how a PM would hand this to management per project.
export function generateSituationReportPdf({ projects, events, summary }) {
  const doc = new jsPDF();
  registerFonts(doc);
  const today = todayStr();

  const totalRequirements = projects.reduce((sum, p) => sum + (p.requirements?.length ?? 0), 0);
  const doneRequirements = projects.reduce((sum, p) => sum + (p.requirements?.filter((r) => r.done).length ?? 0), 0);
  const totalGoals = projects.reduce((sum, p) => sum + (p.goals?.length ?? 0), 0);
  const achievedGoals = projects.reduce((sum, p) => sum + (p.goals?.filter((g) => g.achieved).length ?? 0), 0);

  const dims = projects.flatMap((p) => ['schedule', 'cost', 'quality'].map((k) => p.scorecard?.[k]));
  const overallStatus = dims.includes('red') ? 'red' : dims.includes('amber') ? 'amber' : 'green';

  let y = drawReportHeader(doc, {
    eyebrow: 'Status Report',
    title: projects.length === 1 ? projects[0].name : 'Overall Situation Report',
    generatedLabel: `Generated ${formatDate(today)}   ·   ${projects.map((p) => p.name).join(', ')}`,
    overallStatus: { status: overallStatus },
  });

  y = drawSectionHeader(doc, y, 'Portfolio Health');
  y = drawKpiCards(doc, y, [
    {
      value: summary.overdue_action_items,
      label: 'Overdue Tasks',
      status: summary.overdue_action_items > 0 ? 'red' : 'green',
    },
    {
      value: summary.open_high_severity_pain_points,
      label: 'High Severity Risks',
      status: summary.open_high_severity_pain_points > 0 ? 'red' : 'green',
    },
    {
      value: summary.upcoming_deadlines,
      label: 'Upcoming Milestones',
      status: summary.upcoming_deadlines > 0 ? 'blue' : 'green',
    },
    {
      value: `${doneRequirements}/${totalRequirements}`,
      label: 'Requirements Fulfilled',
      status: fractionStatus(doneRequirements, totalRequirements),
    },
    {
      value: `${achievedGoals}/${totalGoals}`,
      label: 'Goals Achieved',
      status: fractionStatus(achievedGoals, totalGoals),
    },
  ]);

  projects.forEach((project, idx) => {
    if (idx > 0) {
      doc.addPage();
      y = MARGIN + 4;
    } else {
      y = ensureRoom(doc, y, 40);
    }

    const projectEvents = events.filter((e) => e.project_id === project.id);

    y = drawProjectSummaryPanel(doc, y, project);
    y = drawBudgetSection(doc, y, project);

    const openRisks = projectEvents
      .flatMap((e) => e.pain_points.filter((p) => !p.resolved).map((p) => p))
      .sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]);
    y = drawSectionHeader(doc, y, 'Top Risks');
    y = drawRiskCards(doc, y, openRisks, 'No open risks or issues.');

    const openActions = projectEvents
      .flatMap((e) => e.action_items.filter((a) => !a.done))
      .sort((a, b) => (a.due_date || '9999').localeCompare(b.due_date || '9999'));
    y = drawSectionHeader(doc, y, 'Outstanding Actions');
    y = drawTaskList(
      doc,
      y,
      openActions.map((a) => ({
        dueLabel: a.due_date ? formatDate(a.due_date) : '—',
        owner: a.assignee_name || '—',
        text: a.text,
        overdue: isOverdue(a, today),
      })),
      'No open action items.',
    );

    doc.addPage();
    y = MARGIN + 4;

    y = drawSectionHeader(doc, y, 'Requirements');
    y = drawChecklist(
      doc,
      y,
      (project.requirements ?? []).map((r) => ({ done: r.done, text: r.text })),
      'No requirements defined.',
    );

    y = drawSectionHeader(doc, y, 'Goals');
    y = drawChecklist(
      doc,
      y,
      (project.goals ?? []).map((g) => ({
        done: g.achieved,
        text: g.text,
        meta: g.target_date ? formatDate(g.target_date) : null,
      })),
      'No goals defined.',
    );

    const decisions = projectEvents
      .flatMap((e) => e.decisions.map((d) => ({ ...d, eventDate: e.date })))
      .sort((a, b) => a.eventDate.localeCompare(b.eventDate));
    y = drawSectionHeader(doc, y, 'Decisions');
    y = drawDecisionTimeline(
      doc,
      y,
      decisions.map((d) => ({ dateLabel: formatDate(d.eventDate), text: d.text, decidedBy: d.decided_by_name })),
      'No decisions logged.',
    );
  });

  addFooter(doc);
  doc.save(`Statusbericht_${today}.pdf`);
}
